import { computeRiskScore } from "./risk-score";

interface ReportDocument {
  fileName: string;
}

interface ReportIssue {
  type: string;
  severity: string;
  title: string;
  description: string;
  recommendation?: string | null;
  relatedClauseTitle?: string | null;
}

interface ReportClause {
  order: number;
  title: string;
  category?: string | null;
}

interface ReportAnalysis {
  contractType?: string | null;
  contractTypeLabel?: string | null;
  jurisdiction: string;
  partyNames: string[];
  effectiveDate?: string | null;
  summary?: string | null;
  clauses: ReportClause[];
  issues: ReportIssue[];
}

export function generateTextSummary(
  document: ReportDocument,
  analysis: ReportAnalysis
): string {
  const risk = computeRiskScore(analysis.issues);
  const criticalCount = analysis.issues.filter((i) => i.severity === "CRITICAL").length;
  const warningCount = analysis.issues.filter((i) => i.severity === "WARNING").length;
  const infoCount = analysis.issues.filter((i) => i.severity === "INFO").length;

  const lines: string[] = [];

  lines.push(`# Contract Analysis: ${document.fileName}`);
  lines.push("");

  const meta: string[] = [];
  if (analysis.contractTypeLabel) meta.push(`**Type**: ${analysis.contractTypeLabel}`);
  meta.push(`**Jurisdiction**: ${analysis.jurisdiction}`);
  if (analysis.partyNames.length > 0) meta.push(`**Parties**: ${analysis.partyNames.join(", ")}`);
  if (analysis.effectiveDate) meta.push(`**Effective Date**: ${analysis.effectiveDate}`);
  lines.push(meta.join(" | "));
  lines.push("");

  if (analysis.summary) {
    lines.push("## Summary");
    lines.push(analysis.summary);
    lines.push("");
  }

  lines.push("## Risk Assessment");
  lines.push(`Score: ${risk.score}/100 (${risk.label})`);
  lines.push(`- Critical: ${criticalCount} | Warning: ${warningCount} | Info: ${infoCount}`);
  lines.push("");

  if (analysis.issues.length > 0) {
    const sorted = [...analysis.issues].sort((a, b) => {
      const order = { CRITICAL: 0, WARNING: 1, INFO: 2 };
      return (order[a.severity as keyof typeof order] ?? 3) - (order[b.severity as keyof typeof order] ?? 3);
    });

    lines.push("## Issues");
    sorted.forEach((issue, i) => {
      lines.push(`${i + 1}. [${issue.severity}] ${issue.title}`);
      lines.push(`   ${issue.description}`);
      if (issue.recommendation) {
        lines.push(`   Recommendation: ${issue.recommendation}`);
      }
      if (issue.relatedClauseTitle) {
        lines.push(`   Related clause: ${issue.relatedClauseTitle}`);
      }
    });
    lines.push("");
  }

  lines.push(`## Clauses (${analysis.clauses.length} total)`);
  analysis.clauses.forEach((clause) => {
    const cat = clause.category ? ` (${clause.category})` : "";
    lines.push(`${clause.order}. ${clause.title}${cat}`);
  });
  lines.push("");

  lines.push("---");
  lines.push(`Generated by Clausemaster (todo.law) on ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`);

  return lines.join("\n");
}
