import { generateObject } from "ai";
import { getAIModel, getProviderInfo } from "./provider";
import {
  criteriaExtractionSchema,
  guidanceGenerationSchema,
} from "./schemas";
import type {
  CriteriaExtractionResult,
  GuidanceGenerationResult,
} from "./schemas";
import {
  buildCriteriaExtractionPrompt,
  buildGuidanceGenerationPrompt,
} from "./prompts";
import prisma from "@/lib/prisma";

export async function generateAssessmentSkillDraft(
  analysisId: string,
  options?: { anthropicApiKey?: string }
): Promise<string> {
  const startTime = Date.now();

  // Load analysis with clauses
  const analysis = await prisma.analysis.findUnique({
    where: { id: analysisId },
    include: {
      document: true,
      clauses: {
        orderBy: { order: "asc" },
      },
    },
  });

  if (!analysis) {
    throw new Error("Analysis not found");
  }

  if (!analysis.document || analysis.document.status !== "COMPLETED") {
    throw new Error("Analysis must be completed before generating an assessment skill");
  }

  // Create SkillDraft record
  const draft = await prisma.skillDraft.create({
    data: {
      analysisId,
      status: "GENERATING",
      skillType: "ASSESSMENT",
    },
  });

  try {
    const model = getAIModel(options);
    const providerInfo = getProviderInfo();

    // Build classification object from analysis fields
    const classification = {
      contractType: analysis.contractType || "OTHER",
      contractTypeLabel: analysis.contractTypeLabel || analysis.contractType || "Assessment",
      jurisdiction: analysis.jurisdiction as "CALIFORNIA" | "ENGLAND_WALES" | "SPAIN" | "UNKNOWN",
      jurisdictionNotes: analysis.jurisdictionNotes || undefined,
      partyNames: analysis.partyNames,
      effectiveDate: analysis.effectiveDate || undefined,
      summary: analysis.summary || "",
      documentCategory: "assessment" as const,
      partyMode: undefined,
      suggestedDestination: (analysis.suggestedDestination || "dpo-central") as "deal-room" | "dpo-central" | "ai-sentinel",
    };

    // Step 1: Criteria Extraction
    const criteriaResult = await runCriteriaExtraction(
      model,
      analysis.rawExtractedText || "",
      classification
    );

    // Step 2: Guidance Generation
    const guidanceResult = await runGuidanceGeneration(
      model,
      classification,
      criteriaResult
    );

    // Merge guidance into criteria to build full assessmentJson
    const assessmentJson = {
      assessmentType: criteriaResult.assessmentType,
      scoringMethod: criteriaResult.scoringMethod,
      categories: criteriaResult.categories.map((cat) => ({
        ...cat,
        criteria: cat.criteria.map((criterion) => {
          const guidance = guidanceResult.criteria.find(
            (g) => g.criterionId === criterion.id
          );
          return {
            ...criterion,
            guidance: guidance?.guidance,
            remediation: guidance?.remediation,
            evidenceRequired: guidance?.evidenceRequired,
            scoringOptions: guidance?.scoringOptions,
          };
        }),
      })),
    };

    const guidanceJson = guidanceResult;

    // Derive skill metadata
    const contractTypeSlug = (analysis.contractType || "assessment")
      .toLowerCase()
      .replace(/[_\s]+/g, "-");
    const skillId = `com.nel.skills.${contractTypeSlug}`;
    const displayName = analysis.contractTypeLabel || analysis.contractType || "Assessment";
    const language = analysis.jurisdiction === "SPAIN" ? "es" : "en";

    // Map destination
    const destinationMap: Record<string, "DEAL_ROOM" | "DPO_CENTRAL" | "AI_SENTINEL"> = {
      "deal-room": "DEAL_ROOM",
      "dpo-central": "DPO_CENTRAL",
      "ai-sentinel": "AI_SENTINEL",
    };

    const jurisdictions = analysis.jurisdiction !== "UNKNOWN"
      ? [analysis.jurisdiction]
      : ["CALIFORNIA"];

    const metadataJson = {
      contractType: (analysis.contractType || "ASSESSMENT").toUpperCase(),
      displayName: { [language]: displayName },
      description: { [language]: analysis.summary || `${displayName} assessment template generated by Clausemaster AI` },
      version: "1.0",
      assessmentType: criteriaResult.assessmentType,
      scoringMethod: criteriaResult.scoringMethod,
      categoryCount: criteriaResult.categories.length,
      criteriaCount: criteriaResult.categories.reduce((sum, cat) => sum + cat.criteria.length, 0),
      languages: [language],
      jurisdictions,
    };

    const manifestJson = {
      skillId,
      name: (analysis.contractType || "ASSESSMENT").toUpperCase(),
      displayName,
      version: "1.0.0",
      jurisdictions,
      languages: [language],
      author: "Clausemaster AI",
      license: "proprietary",
      templateFamily: (analysis.contractType || "ASSESSMENT").toUpperCase(),
      nativeJurisdiction: jurisdictions[0],
      skillType: "assessment",
    };

    const processingTimeMs = Date.now() - startTime;

    // Update the draft with all generated data
    await prisma.skillDraft.update({
      where: { id: draft.id },
      data: {
        status: "REVIEW",
        skillType: "ASSESSMENT",
        destination: analysis.suggestedDestination
          ? destinationMap[analysis.suggestedDestination] || null
          : null,
        skillId,
        contractType: (analysis.contractType || "ASSESSMENT").toUpperCase(),
        displayName,
        assessmentJson,
        guidanceJson,
        metadataJson,
        manifestJson,
        aiProvider: providerInfo.provider,
        aiModel: providerInfo.model,
        processingTimeMs,
      },
    });

    return draft.id;
  } catch (error) {
    console.error(`Assessment skill generation failed for analysis ${analysisId}:`, error);
    await prisma.skillDraft.update({
      where: { id: draft.id },
      data: {
        status: "FAILED",
        errorMessage: error instanceof Error ? error.message : "Assessment skill generation failed",
      },
    });
    throw error;
  }
}

async function runCriteriaExtraction(
  model: Parameters<typeof generateObject>[0]["model"],
  text: string,
  classification: Parameters<typeof buildCriteriaExtractionPrompt>[1]
): Promise<CriteriaExtractionResult> {
  const prompt = buildCriteriaExtractionPrompt(text, classification);
  const result = await generateObject({
    model,
    schema: criteriaExtractionSchema,
    prompt,
  });
  return result.object;
}

async function runGuidanceGeneration(
  model: Parameters<typeof generateObject>[0]["model"],
  classification: Parameters<typeof buildGuidanceGenerationPrompt>[0],
  criteria: CriteriaExtractionResult
): Promise<GuidanceGenerationResult> {
  const prompt = buildGuidanceGenerationPrompt(classification, criteria);
  const result = await generateObject({
    model,
    schema: guidanceGenerationSchema,
    prompt,
  });
  return result.object;
}
