import { generateObject } from "ai";
import { getAIModel, getProviderInfo } from "./provider";
import {
  optionGenerationSchema,
  boilerplateGenerationSchema,
} from "./schemas";
import type {
  OptionGenerationResult,
  BoilerplateGenerationResult,
} from "./schemas";
import {
  buildOptionGenerationPrompt,
  buildBoilerplateGenerationPrompt,
} from "./prompts";
import prisma from "@/lib/prisma";

export async function generateSkillDraft(analysisId: string): Promise<string> {
  const startTime = Date.now();

  // Load analysis with clauses and issues
  const analysis = await prisma.analysis.findUnique({
    where: { id: analysisId },
    include: {
      document: true,
      clauses: {
        orderBy: { order: "asc" },
      },
      issues: true,
    },
  });

  if (!analysis) {
    throw new Error("Analysis not found");
  }

  if (!analysis.document || analysis.document.status !== "COMPLETED") {
    throw new Error("Analysis must be completed before generating a skill");
  }

  if (analysis.clauses.length === 0) {
    throw new Error("Analysis has no extracted clauses");
  }

  // Create SkillDraft record
  const draft = await prisma.skillDraft.create({
    data: {
      analysisId,
      status: "GENERATING",
    },
  });

  try {
    const model = getAIModel();
    const providerInfo = getProviderInfo();

    // Build classification object from analysis fields
    const classification = {
      contractType: analysis.contractType || "OTHER",
      contractTypeLabel: analysis.contractTypeLabel || analysis.contractType || "Contract",
      jurisdiction: analysis.jurisdiction as "CALIFORNIA" | "ENGLAND_WALES" | "SPAIN" | "UNKNOWN",
      jurisdictionNotes: analysis.jurisdictionNotes || undefined,
      partyNames: analysis.partyNames,
      effectiveDate: analysis.effectiveDate || undefined,
      summary: analysis.summary || "",
    };

    // Build clauses in the format expected by prompts
    const extractedClauses = analysis.clauses.map((c) => ({
      title: c.title,
      category: c.category || undefined,
      originalText: c.originalText,
      summary: c.summary || "",
      legalSignificance: c.legalSignificance || undefined,
      skillClauseMatch: c.skillClauseMatch || undefined,
      biasAssessment: c.biasAssessment === "FAVORS_PARTY_A"
        ? "favors-party-a" as const
        : c.biasAssessment === "FAVORS_PARTY_B"
        ? "favors-party-b" as const
        : "neutral" as const,
    }));

    // Step 4: Option Generation
    const optionResult = await runOptionGeneration(
      model,
      analysis.rawExtractedText || "",
      classification,
      extractedClauses
    );

    // Step 5: Boilerplate Generation
    const clauseTitles = optionResult.clauses.map((c) => c.title);
    const boilerplateResult = await runBoilerplateGeneration(
      model,
      classification,
      clauseTitles
    );

    // Derive skill metadata
    const contractTypeSlug = (analysis.contractType || "contract")
      .toLowerCase()
      .replace(/[_\s]+/g, "-");
    const skillId = `com.nel.skills.${contractTypeSlug}`;
    const displayName = analysis.contractTypeLabel || analysis.contractType || "Contract";

    // Detect language from jurisdiction
    const language = analysis.jurisdiction === "SPAIN" ? "es" : "en";

    // Build clauses.json structure (wrapping strings in i18n objects)
    const clausesJson = buildClausesJson(
      analysis.contractType || "CONTRACT",
      displayName,
      optionResult,
      language
    );

    // Build metadata
    const metadataJson = {
      contractType: (analysis.contractType || "CONTRACT").toUpperCase(),
      displayName,
      description: analysis.summary || `${displayName} template generated by Clausemaster AI`,
      version: "1.0",
      clauseCount: optionResult.clauses.length,
    };

    // Build manifest
    const jurisdictions = analysis.jurisdiction !== "UNKNOWN"
      ? [analysis.jurisdiction]
      : ["CALIFORNIA"];
    const manifestJson = {
      skillId,
      name: (analysis.contractType || "CONTRACT").toUpperCase(),
      displayName,
      version: "1.0.0",
      jurisdictions,
      languages: [language],
      author: "Clausemaster AI",
      license: "proprietary",
      templateFamily: (analysis.contractType || "CONTRACT").toUpperCase(),
      nativeJurisdiction: jurisdictions[0],
    };

    const processingTimeMs = Date.now() - startTime;

    // Update the draft with all generated data
    await prisma.skillDraft.update({
      where: { id: draft.id },
      data: {
        status: "REVIEW",
        skillId,
        contractType: (analysis.contractType || "CONTRACT").toUpperCase(),
        displayName,
        clausesJson,
        boilerplateJson: boilerplateResult,
        metadataJson,
        manifestJson,
        aiProvider: providerInfo.provider,
        aiModel: providerInfo.model,
        processingTimeMs,
      },
    });

    return draft.id;
  } catch (error) {
    console.error(`Skill generation failed for analysis ${analysisId}:`, error);
    await prisma.skillDraft.update({
      where: { id: draft.id },
      data: {
        status: "FAILED",
        errorMessage: error instanceof Error ? error.message : "Skill generation failed",
      },
    });
    throw error;
  }
}

function buildClausesJson(
  contractType: string,
  displayName: string,
  optionResult: OptionGenerationResult,
  language: string
) {
  return {
    contractType: contractType.toUpperCase(),
    displayName: { [language]: displayName },
    description: { [language]: `${displayName} template` },
    version: "1.0",
    clauses: optionResult.clauses.map((clause) => ({
      id: clause.id,
      title: { [language]: clause.title },
      category: clause.category,
      order: clause.order,
      plainDescription: { [language]: clause.plainDescription },
      legalContext: clause.legalContext
        ? { [language]: clause.legalContext }
        : undefined,
      isRequired: clause.isRequired,
      options: clause.options.map((opt) => ({
        id: opt.id,
        code: opt.code,
        label: { [language]: opt.label },
        order: opt.order,
        plainDescription: { [language]: opt.plainDescription },
        prosPartyA: { [language]: opt.prosPartyA },
        consPartyA: { [language]: opt.consPartyA },
        prosPartyB: { [language]: opt.prosPartyB },
        consPartyB: { [language]: opt.consPartyB },
        legalText: { [language]: opt.legalText },
        biasPartyA: opt.biasPartyA,
        biasPartyB: opt.biasPartyB,
      })),
    })),
  };
}

async function runOptionGeneration(
  model: Parameters<typeof generateObject>[0]["model"],
  contractText: string,
  classification: Parameters<typeof buildOptionGenerationPrompt>[1],
  clauses: Parameters<typeof buildOptionGenerationPrompt>[2]
): Promise<OptionGenerationResult> {
  const prompt = buildOptionGenerationPrompt(contractText, classification, clauses);
  const result = await generateObject({
    model,
    schema: optionGenerationSchema,
    prompt,
  });
  return result.object;
}

async function runBoilerplateGeneration(
  model: Parameters<typeof generateObject>[0]["model"],
  classification: Parameters<typeof buildBoilerplateGenerationPrompt>[0],
  clauseTitles: string[]
): Promise<BoilerplateGenerationResult> {
  const prompt = buildBoilerplateGenerationPrompt(classification, clauseTitles);
  const result = await generateObject({
    model,
    schema: boilerplateGenerationSchema,
    prompt,
  });
  return result.object;
}
